### PR TITLE
Add OSINT tools

### PR DESCRIPTION
**Pull request by kriptonian1**
# Add OSINT tools to help folks with OSINT investigation 
solved issue #13 
### tools added:
- `PimEyes` for deep face search
- ` OSINT Framework` lists many useful OSINT tools
- `TinEye` reverse image search
- `Depix` un-blur blurred texts
- `Osintgram` Instagram OSINT
- `Sherlock` reverse username search
- `PhoneInfoga` phone number info search

### CODE REVIEW

**Comment by kriptonian1** [comment]
Hey, @hhhrrrttt222111  can you pls label this as `hacktoberfest-accepted` if this commit is acceptable

**Comment by kriptonian1** [comment]
@hhhrrrttt222111  Can pls label it as `hacktoberfest-accepted`

**Comment by kriptonian1** [comment]
thanks, Happy hacking

**Comment by kriptonian1** [comment]
Hey @hhhrrrttt222111, it's saying you are not participating 
image

**Comment by hhhrrrttt222111** [comment]
> Hey @hhhrrrttt222111, it's saying you are not participating image

Try after 12am

**Comment by kriptonian1** [comment]
They have counted the previous project I worked on

**Comment by rfierro223** [comment]
Great job

**Pull request merged**
